const Data = {
	data: [
		{
			id: '1',
			category: '存货',
			business: '购买原材料',
			explanation: '小规模纳税人',
			result: '原材料',
			source: '银行存款',
		},
		{
			id: '2',
			category: '存货',
			business: '购买原材料',
			explanation: '一般纳税人，增值税专用发票',
			result: '原材料\r\n应交税费——应交增值税（进项税额）',
			source: '银行存款',
		},
		{
			id: '3',
			category: '存货',
			business: '预付款，未取得商品',
			explanation: '采购用于广告营销活动的特定商品，不作为存货成本',
			result: '预付账款',
			source: '银行存款',
		},
		{
			id: '4',
			category: '存货',
			business: '预付款，取得商品',
			explanation: '采购用于广告营销活动的特定商品，不作为存货成本',
			result: '销售费用',
			source: '预付账款',
		},
		{
			id: '5',
			category: '存货',
			business: '销售商品',
			explanation: '确认收入',
			result: '应收账款/合同资产/银行存款',
			source: '主营业务收入\r\n应交税费——应交增值税（销项税额）',
		},
		{
			id: '6',
			category: '存货',
			business: '销售商品',
			explanation: '确认成本',
			result: '主营业务成本\r\n存货跌价准备',
			source: '库存商品',
		},
		{
			id: '7',
			category: '存货',
			business: '销售原材料',
			explanation: '确认收入',
			result: '应收账款/合同资产/银行存款',
			source: '其他业务收入\r\n应交税费——应交增值税（销项税额）',
		},
		{
			id: '8',
			category: '存货',
			business: '销售原材料',
			explanation: '确认成本',
			result: '其他业务成本\r\n存货跌价准备',
			source: '原材料',
		},
		{
			id: '9',
			category: '存货',
			business: '生产领用的包装物',
			explanation: '包装物',
			result: '制造费用',
			source: '周转材料——包装物',
		},
		{
			id: '10',
			category: '存货',
			business: '出借包装物及随同产品出售不单独计价的包装物',
			explanation: '不收钱',
			result: '销售费用',
			source: '周转材料——包装物',
		},
		{
			id: '11',
			category: '存货',
			business: '出租包装物及随同产品出售单独计价的包装物',
			explanation: '收钱',
			result: '其他业务成本',
			source: '周转材料——包装物',
		},
		{
			id: '12',
			category: '存货',
			business: '存货成本高于可变现净值',
			explanation: '应当计提存货跌价准备',
			result: '资产减值损失——存货减值损失',
			source: '存货跌价准备',
		},
		{
			id: '13',
			category: '存货',
			business: '以前减记存货价值的影响因素已经消失',
			explanation: '转回存货跌价准备',
			result: '存货跌价准备',
			source: '资产减值损失——存货减值损失',
		},
		{
			id: '14',
			category: '存货',
			business: '销售已经计提了的商品/原材料',
			explanation: '按比例结转存货跌价准备',
			result: '存货跌价准备',
			source: '主营业务成本',
		},
		{
			id: '15',
			category: '存货',
			business: '存货盘盈',
			explanation: '批准前',
			result: '原材料/库存商品',
			source: '待处理财产损溢',
		},
		{
			id: '16',
			category: '存货',
			business: '存货盘盈',
			explanation: '批准后',
			result: '待处理财产损益',
			source: '管理费用',
		},
		{
			id: '17',
			category: '存货',
			business: '存货盘亏或毁损',
			explanation: '批准前',
			result: '待处理财产损溢',
			source: '原材料/库存商品',
		},
		{
			id: '18',
			category: '存货',
			business: '存货人为盘亏或毁损',
			explanation: '批准后，其他应收款是赔款，管理费用是扣除赔款后的净损失',
			result: '管理费用\r\n其他应收款',
			source: '待处理财产损益',
		},
		{
			id: '19',
			category: '存货',
			business: '存货因自然灾害盘亏或毁损',
			explanation: '批准前',
			result: '待处理财产损溢',
			source: '原材料/库存商品',
		},
		{
			id: '20',
			category: '存货',
			business: '存货因自然灾害盘亏或毁损',
			explanation: '批准后',
			result: '营业外支出\r\n其他应收款',
			source: '待处理财产损益',
		},
		{
			id: '21',
			category: '固定资产',
			business: '购买设备',
			explanation: '支付价款、增值税',
			result: '在建工程——xx设备\r\n应缴税费——应交增值税（进项税额）',
			source: '银行存款/其他应付款/应付票据',
		},
		{
			id: '22',
			category: '固定资产',
			business: '安装设备',
			explanation: '领用本公司原材料、支付安装工人工资',
			result: '在建工程——xx设备',
			source: '原材料\r\n应付职工薪酬',
		},
		{
			id: '23',
			category: '固定资产',
			business: '设备安装完毕达到预定可使用状态',
			explanation: '转入固定资产',
			result: '固定资产——xx设备',
			source: '在建工程——xx设备',
		},
		{
			id: '24',
			category: '固定资产',
			business: '分期付款购买资产',
			explanation: '超出正常信用条件，具有融资性质，分为购买价款的现值+利息总和两部分',
			result: '在建工程——xx设备\r\n未确认融资费用',
			source: '长期应付款——x公司',
		},
		{
			id: '25',
			category: '固定资产',
			business: '分期偿还',
			explanation: '达到预定可使用状态前，每期还的利息=期末本金余额*利率',
			result: '在建工程——xx设备',
			source: '未确认融资费用',
		},
		{
			id: '26',
			category: '固定资产',
			business: '分期偿还',
			explanation: '达到预定可使用状态后，每期还的利息=期末本金余额*利率',
			result: '财务费用',
			source: '未确认的融资费用',
		},
		{
			id: '27',
			category: '固定资产',
			business: '分期偿还',
			explanation: '分期付款额',
			result: '长期应付款——x公司',
			source: '银行贷款',
		},
		{
			id: '28',
			category: '固定资产',
			business: '自行建造固定资产完工后，剩余工程物资转作企业存货',
			explanation: '按实际成本',
			result: '原材料',
			source: '工程物资',
		},
		{
			id: '29',
			category: '固定资产',
			business: '盘亏——未完工',
			explanation: '达到预定可使用状态前',
			result: '在建工程',
			source: '工程物资',
		},
		{
			id: '30',
			category: '固定资产',
			business: '盘亏——已完工',
			explanation: '或者自然灾害导致的盘亏，达到预定可使用状态后',
			result: '营业外支出',
			source: '工程物资',
		},
		{
			id: '31',
			category: '固定资产',
			business: '盘盈',
			explanation: '达到预定可使用状态前',
			result: '工程物资',
			source: '在建工程',
		},
		{
			id: '32',
			category: '固定资产',
			business: '盘盈',
			explanation: '达到预定可使用状态后',
			result: '工程物资',
			source: '营业外收入',
		},
		{
			id: '33',
			category: '固定资产',
			business: '计提安全生产费',
			explanation: '按月提取安全生产费',
			result: '生产成本/制造费用',
			source: '专项储备——安全生产费',
		},
		{
			id: '34',
			category: '固定资产',
			business: '使用安全生产费',
			explanation: '形成固定资产，达到预定可使用状态前',
			result: '在建工程\r\n应缴税费——应交增值税（进项税额）',
			source: '银行存款',
		},
		{
			id: '35',
			category: '固定资产',
			business: '使用安全生产费',
			explanation: '形成固定资产，达到预定可使用状态后时，全额计提累计折旧',
			result: '专项储备——安全生产费',
			source: '累计折旧',
		},
		{
			id: '36',
			category: '固定资产',
			business: '使用安全生产费',
			explanation: '费用性支出，完工过年后的安全生产检查费',
			result: '专项储备——安全生产费',
			source: '银行存款',
		},
		{
			id: '37',
			category: '固定资产',
			business: '试车期间取得的收入',
			explanation: '冲减工程成本',
			result: '银行存款',
			source: '在建工程',
		},
		{
			id: '38',
			category: '固定资产',
			business: '存在弃置费用的固定资产完工',
			explanation: '弃置费用按照使用寿命和实际利率计算现值',
			result: '固定资产——xx核反应堆',
			source: '在建工程——xx核反应堆\r\n预计负债——xx核反应堆——弃置费用',
		},
		{
			id: '39',
			category: '固定资产',
			business: '弃置费用按期分摊',
			explanation: '每年计算实际利息，计入财务费用',
			result: '财务费用',
			source: '预计负债——xx核反应堆——弃置费用',
		},
		{
			id: '40',
			category: '固定资产',
			business: '计提折旧',
			explanation: '按月计提',
			result: '制造费用——xx车间\r\n管理费用\r\n销售费用',
			source: '累计折旧',
		},
		{
			id: '41',
			category: '固定资产',
			business: '固定资产更新改造',
			explanation: '固定资产转入改扩建，停止折旧',
			result: '在建工程——xx生产线\r\n累计折旧',
			source: '固定资产——xx生产线',
		},
		{
			id: '42',
			category: '固定资产',
			business: '固定资产更新改造完成',
			explanation: '转回固定资产，重新开始折旧，按照新的寿命，净残值，折旧方法折旧',
			result: '固定资产——xx生产线',
			source: '在建工程——xx生产线',
		},
		{
			id: '43',
			category: '固定资产',
			business: '替换原固定资产的某组成部分',
			explanation: '原某组件报废',
			result: '营业外支出',
			source: '在建工程——xx组件',
		},
		{
			id: '44',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '转入清理：固定资产账面价值，已计提的折旧，已计提的减值准备',
			result: '固定资产清理\r\n累计折旧\r\n固定资产减值准备',
			source: '固定资产',
		},
		{
			id: '45',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '发生清理费用：清理过程中发生的费用及税费',
			result: '固定资产清理',
			source: '银行存款\r\n应交税费',
		},
		{
			id: '46',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '出售收入和残料等处理',
			result: '银行存款\r\n原材料',
			source: '固定资产清理\r\n应交税费——应交增值税',
		},
		{
			id: '47',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '保险赔偿处理',
			result: '其他应收款\r\n银行存款',
			source: '固定资产清理',
		},
		{
			id: '48',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '清理完成后正常出售转让的净收入',
			result: '资产处置损益',
			source: '固定资产清理',
		},
		{
			id: '49',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '清理完成后正常出售转让的净损失',
			result: '固定资产清理',
			source: '资产处置损失',
		},
		{
			id: '50',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '清理完成后正常报废的净收入',
			result: '营业外支出——非流动资产报废',
			source: '固定资产清理',
		},
		{
			id: '51',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '清理完成后正常报废的净损失',
			result: '固定资产清理',
			source: '营业外支出——非流动资产报废',
		},
		{
			id: '52',
			category: '固定资产',
			business: '固定资产处置',
			explanation: '自然灾害',
			result: '固定资产清理',
			source: '营业外支出——非常损失',
		},
		{
			id: '53',
			category: '固定资产',
			business: '固定资产清查',
			explanation: '盘盈',
			result: '固定资产',
			source: '以前年度损益调整',
		},
		{
			id: '54',
			category: '固定资产',
			business: '固定资产清查',
			explanation: '盘亏，批准前，待处理固定资产损益：盘亏部分的账面价值，累计折旧：已计提的累计折旧，减值准备：已计提的减值准备',
			result: '待处理财产损溢——待处理固定资产损益\r\n累计折旧\r\n固定资产减值准备',
			source: '固定资产',
		},
		{
			id: '55',
			category: '固定资产',
			business: '固定资产清查',
			explanation: '盘亏，批准后，其他应收款：可收回的部分。',
			result: '其他应收款\r\n营业外支出——盘亏损失',
			source: '待处理财产损溢',
		},
		{
			id: '56',
			category: '无形资产',
			business: '购买专利',
			explanation: '直接交易',
			result: '无形资产——专利权',
			source: '银行存款',
		},
		{
			id: '57',
			category: '无形资产',
			business: '购买商标',
			explanation: '分期付款，第一笔，无形资产取现值，融资费用取剩余的值，即利息现值',
			result: '无形资产——商标权\r\n未确认融资费用',
			source: '长期应付款',
		},
		{
			id: '58',
			category: '无形资产',
			business: '购买商标',
			explanation: '年底付款，实际付款',
			result: '长期应付款',
			source: '银行存款',
		},
		{
			id: '59',
			category: '无形资产',
			business: '购买商标',
			explanation: '年底付款，利息部分的处理，利息=上期融资余额*利率（没还的本金*利率）',
			result: '财务费用',
			source: '未确认的融资费用',
		},
		{
			id: '60',
			category: '无形资产',
			business: '投资者投入商标权',
			explanation: '包含相关税费',
			result: '无形资产——商标权',
			source: '实收资本（或股本）\r\n银行存款',
		},
		{
			id: '61',
			category: '无形资产',
			business: '购买土地使用权',
			explanation: '支付转让价款',
			result: '无形资产——土地使用权',
			source: '银行存款',
		},
		{
			id: '62',
			category: '无形资产',
			business: '取得使用权的土地上，自行建造厂房',
			explanation: '自行建造',
			result: '在建工程',
			source: '工程物资\r\n应付职工薪酬\r\n银行存款',
		},
		{
			id: '63',
			category: '无形资产',
			business: '取得使用权的土地上，建造的厂房达到预定可使用状态',
			explanation: '完工',
			result: '固定资产',
			source: '在建工程',
		},
		{
			id: '64',
			category: '无形资产',
			business: '摊销土地使用权和折旧厂房',
			explanation: '土地摊销\r\n厂房折旧',
			result: '制造费用（土地摊销）\r\n制造费用（厂房折旧）',
			source: '累计摊销\r\n累计折旧',
		},
		{
			id: '65',
			category: '无形资产',
			business: '开发无形资产',
			explanation: '不满足资本化条件',
			result: '研究支出——费用化支出',
			source: '原材料\r\n银行存款\r\n应付职工薪酬',
		},
		{
			id: '66',
			category: '无形资产',
			business: '开发无形资产',
			explanation: '满足资本化条件',
			result: '研究支出——资本化支出',
			source: '原材料\r\n银行存款\r\n应付职工薪酬',
		},
		{
			id: '67',
			category: '无形资产',
			business: '开发无形资产',
			explanation: '专利技术达到预定可使用状态，费用化支出进管理费用，资本化支出，进无形资产',
			result: '管理费用\r\n无形资产',
			source: '研究支出——费用化支出\r\n研究支出——资本化支出',
		},
		{
			id: '68',
			category: '无形资产',
			business: '按年摊销无形资产',
			explanation: '寿命有限，待摊销金额/使用寿命',
			result: '制造费用——非专利技术\r\n管理费用——商标权',
			source: '累计摊销',
		},
		{
			id: '69',
			category: '无形资产',
			business: '无形资产减值',
			explanation: '平时不摊销，每年进行减值测试',
			result: '资产减值损失',
			source: '无形资产减值准备——商标权',
		},
		{
			id: '70',
			category: '无形资产',
			business: '出租无形资产——专利',
			explanation: '取得使用费',
			result: '银行存款',
			source: '其他业务收入',
		},
		{
			id: '71',
			category: '无形资产',
			business: '出租无形资产——专利',
			explanation: '按年摊销专利技术',
			result: '其他业务成本',
			source: '累计摊销',
		},
		{
			id: '72',
			category: '无形资产',
			business: '无形资产报废',
			explanation: '已计提的累计摊销+已计提的减值准备 = 无形资产账面价值+营业外支出。',
			result: '累计摊销\r\n无形资产减值准备',
			source: '无形资产\r\n营业外支出',
		},
		{
			id: '73',
			category: '投资性房地产',
			business: '扩建投资性房地产',
			explanation: '转入扩建工程时',
			result: '投资性房地产——厂房（在建）\r\n投资性房地产累计折旧',
			source: '投资性房地产——厂房',
		},
		{
			id: '74',
			category: '投资性房地产',
			business: '扩建投资性房地产',
			explanation: '扩建开销',
			result: '投资性房地产——厂房（在建）',
			source: '银行存款',
		},
		{
			id: '75',
			category: '投资性房地产',
			business: '扩建投资性房地产',
			explanation: '完工',
			result: '投资性房地产——厂房',
			source: '投资性房地产——厂房（在建）',
		},
		{
			id: '76',
			category: '投资性房地产',
			business: '费用化后续支出',
			explanation: '不满足投资性房地产确认条件的，日常维护发生的支出',
			result: '其他业务成本',
			source: '银行存款',
		},
		{
			id: '77',
			category: '投资性房地产',
			business: '成本模式后续计量投资性房地产',
			explanation: '按期（月）计提折旧或摊销',
			result: '其他业务成本',
			source: '投资性房地产累计折旧（摊销）',
		},
		{
			id: '78',
			category: '投资性房地产',
			business: '成本模式后续计量投资性房地产',
			explanation: '租金收入',
			result: '银行存款',
			source: '其他业务收入',
		},
		{
			id: '79',
			category: '投资性房地产',
			business: '成本模式后续计量投资性房地产',
			explanation: '减值测试后确定发生减值的',
			result: '资产减值损失',
			source: '投资性房地产减值准备',
		},
		{
			id: '80',
			category: '投资性房地产',
			business: '公允价值模式后续计量投资性房地产',
			explanation: '不计提折旧或摊销',
			result: '投资性房地产——公允价值变动',
			source: '公允价值变动损益',
		},
		{
			id: '81',
			category: '投资性房地产',
			business: '成本模式，投资性房地产开始自用',
			explanation: '固定资产，房子',
			result: '固定资产\r\n投资性房地产累计折旧\r\n投资性房地产减值准备',
			source: '投资性房地产\r\n累计折旧\r\n固定资产减值准备',
		},
		{
			id: '82',
			category: '投资性房地产',
			business: '成本模式，投资性房地产开始自用',
			explanation: '无形资产，土地使用权',
			result: '无形资产\r\n投资性房地产累计摊销\r\n投资性房地产减值准备',
			source: '投资性房地产\r\n累计摊销\r\n无形资产减值准备',
		},
		{
			id: '83',
			category: '投资性房地产',
			business: '公允价值模式，投资性地产开始自用',
			explanation: '固定资产，公允价值增多',
			result: '固定资产',
			source: '投资性房地产——成本\r\n投资性房地产——公允价值变动\r\n公允价值变动损益',
		},
		{
			id: '84',
			category: '投资性房地产',
			business: '公允价值模式，投资性地产开始自用',
			explanation: '固定资产，公允价值减少',
			result: '固定资产\r\n投资性房地产——公允价值变动\r\n公允价值变动损益',
			source: '投资性房地产——成本',
		},
		{
			id: '85',
			category: '投资性房地产',
			business: '成本模式，投资性房地产转存货',
			explanation: '租赁期满，或者决定重新开发出售',
			result: '开发产品\r\n投资性房地产累计折旧\r\n投资性房地产减值准备',
			source: '投资性房地产',
		},
		{
			id: '86',
			category: '投资性房地产',
			business: '公允价值模式，投资性房地产转存货',
			explanation: '升值',
			result: '开发产品',
			source: '投资性房地产——成本\r\n投资性房地产——公允价值变动\r\n公允价值变动损益',
		},
		{
			id: '87',
			category: '投资性房地产',
			business: '公允价值模式，投资性房地产转存货',
			explanation: '贬值',
			result: '开发产品\r\n投资性房地产——公允价值变动\r\n公允价值变动损益',
			source: '投资性房地产——成本',
		},
		{
			id: '88',
			category: '投资性房地产',
			business: '存货，转为投资性房地产',
			explanation: '成本模式',
			result: '投资性房地产\r\n存货跌价准备',
			source: '开发产品',
		},
		{
			id: '89',
			category: '投资性房地产',
			business: '自用房，转为投资性房地产',
			explanation: '成本模式，固定资产',
			result: '投资性房地产\r\n累计折旧\r\n固定资产减值准备',
			source: '固定资产\r\n投资性房地产累计折旧（摊销）\r\n投资性房地产减值准备',
		},
		{
			id: '90',
			category: '投资性房地产',
			business: '自用房，转为投资性房地产',
			explanation: '成本模式，无形资产（土地使用权）',
			result: '投资性房地产\r\n累计摊销\r\n无形资产减值准备',
			source: '无形资产\r\n投资性房地产累计折旧（摊销）\r\n投资性房地产减值准备',
		},
		{
			id: '91',
			category: '投资性房地产',
			business: '存货，转为投资性房地产',
			explanation: '公允价值模式，升值',
			result: '投资性房地产——成本\r\n存货跌价准备',
			source: '开发产品\r\n其他综合收益',
		},
		{
			id: '92',
			category: '投资性房地产',
			business: '存货，转为投资性房地产',
			explanation: '公允价值模式，贬值',
			result: '投资性房地产——成本\r\n存货跌价准备\r\n公允价值变动损益',
			source: '开发产品',
		},
		{
			id: '93',
			category: '投资性房地产',
			business: '自用房，转为投资性房地产',
			explanation: '公允价值模式，固定资产，升值',
			result: '投资性房地产——成本\r\n累计折旧\r\n固定资产减值准备',
			source: '固定资产\r\n其他综合收益',
		},
		{
			id: '94',
			category: '投资性房地产',
			business: '自用房，转为投资性房地产',
			explanation: '公允价值模式，无形资产，升值',
			result: '投资性房地产——成本\r\n累计摊销\r\n固定资产减值准备',
			source: '无形资产\r\n其他综合收益',
		},
		{
			id: '95',
			category: '投资性房地产',
			business: '自用房，转为投资性房地产',
			explanation: '公允价值模式，固定资产，贬值',
			result: '投资性房地产——成本\r\n累计折旧\r\n固定资产减值准备\r\n公允价值变动损益',
			source: '固定资产',
		},
		{
			id: '96',
			category: '投资性房地产',
			business: '自用房，转为投资性房地产',
			explanation: '公允价值模式，无形资产，贬值',
			result: '投资性房地产——成本\r\n累计摊销\r\n固定资产减值准备\r\n公允价值变动损益',
			source: '无形资产',
		},
	],
};

export default Data;
